on:
  pull_request:
    paths:
    - '**/*.ts'
    - .github/workflows/ci.yml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
        env:
          NODE_ENV: development
      - run: npm test
  check-generated-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm run dist
      - run: git diff --exit-code
